### ISSUE TITLE
Get error 500 when create first Admin user on https

### ISSUE THREAD

**Issue by mariushosting** [gyaaniguy/personal-drive#8]
Get always error 500 when create First Admin user on https

**Comment by gyaaniguy** [comment]
@mariushosting does the issue persist on latest docker ?

**Comment by CreakyLid** [comment]
> [@mariushosting](https://github.com/mariushosting) does the issue persist on latest docker ?

I believe I am on the latest docker and I am still getting this issue!

(see above my last reply with more info of my instance - lemme know if you can't see it !)

**Comment by gyaaniguy** [comment]
Thanks so much CreakyLid for all that info. I'll explore this..

Just for trying can you try giving `{myUnraidstoragepath}` 777 permissions ?

**Comment by CreakyLid** [comment]
> Thanks so much CreakyLid for all that info. I'll explore this..
> 
> Just for trying can you try giving `{myUnraidstoragepath}` 777 permissions ?

Of course! No problem at all ! :D

And after checking, I believe my storage path already had 777 permissions- but i have made sure they do now, just to check, and that didn't seem to change anything..!

**Comment by gyaaniguy** [comment]
ok I think I can replicate it. Update soon

**Comment by gyaaniguy** [comment]
I have pushed a change. Please try.. 

Info: So if database/database.sqlite has insufficient permissions, then the application used to throw a 500. I have made some changes so the application 1) handles bad permission better, informs user 2) Creates the database.sqlite in docker with better permissions.
I cannot be 100% sure if this was indeed the problem. 
Thank you

**Comment by VBman** [comment]
Sorry about the delay.

That's fixed the error for me now and everything is working on Debian 12, thank you!

**Comment by CreakyLid** [comment]
Not sure if I have maybe broken something different somewhere then on my part, but my Unraid docker is still broken! (although it seems to be a different kind of broken now)

I gave my Docker compose an update.

Instead of before where I would get to the login page, and when filling out the boxes to login it would go to the Error 500 page - instead, now when I fill out my details and click login, it just sorta doesn't do _anything_! The username box stays filled out, but the password box goes blank and nothing happens.

Is there anything helpful can get from logs or anything?
I had a look at logs, and although I do not understand exactly what it's showing, there _are_ "POST" and "GET" entries in the log timestamped when I click login, and device info etc.

**Comment by gyaaniguy** [comment]
@CreakyLid well there are few places for logs - 
1) In docker - /var/www/html/personal-drive/storage/logs/laravel.log
2) In browser - Dev tools (F12) -> Console tab - anything in red
3) In browser - Network tab -> Now click 'login' -> is there a new request? -> see its 'response'

Would to be great if I can have any. especially 1 OR 2

Thank you

**Comment by gyaaniguy** [comment]
@CreakyLid okay 2 things -
1. I have updated the docker image again. Issue was with the request throttle wasn't showing any error message. So it would reject and blank out the password field and not show any message. Please try again
2. From the log you shared, it seems to be a broken install. try deleting the database/database.sqlite file 

```
docker compose pull && docker compose up --force-recreate
```

**Comment by CreakyLid** [comment]
Now I am back to getting the `500 | SERVER ERROR` !! 😭

@gyaaniguy I updated the stack once more, and also deleted the database file in my appdata folder.
When I loaded the WebUI I was prompted to create an admin user again. I used the same credentials as I had originally. It did the same thing where it showed the `500 | SERVER ERROR` , then refreshing took me to the login page, however every time I tried to login I got the `500 | SERVER ERROR` .

I totally removed the Docker compose from my Unraid, and deleted the appdata folder.
Again though, the same process happened (i tried with new credentials this time)~ had to create new admin account, got the `500 | SERVER ERROR`, refreshed, and each time I try to login again now I am hit with a `500 | SERVER ERROR`.

If I try to login with either the new credentials I just created now, or the old login credentials which in theory shouldn't work this time rounnd, I am taken to the `500 | SERVER ERROR` screen. There is no 'incorrect login' type message or anythin'.

Here's a new laravel log if that helps! WHich, by the looks of it, also has general errors too. Although again they don't mean much to me unfortunately.
Anything else you might find helpful lemme know!

[new laravel-log.txt](https://github.com/user-attachments/files/19720446/new.laravel-log.txt)

**Comment by gyaaniguy** [comment]
Ahh I figured it out !! It was very tricky. 
Issue: Since a local empty database folder was mapped, it was overwriting the docker image database folder which had the migration files ! Hence no tables were being created.

      - {myUnraidappdatapath}:/var/www/html/personal-drive/database

Its late here, and I don't want to rush. Will send a fix tommorow. 
Thanks so much @CreakyLid !

**Comment by gyaaniguy** [comment]
@CreakyLid have a fix. please do try.

NOTE: BREAKING CHANGE!!

- database location has changed ! its now  database/db/database.sqlite
- the docker_compose.yml file has changed to accomodate this

So your 
`{myUnraidappdatapath}:/var/www/html/personal-drive/database` is now       `{myUnraidappdatapath}:/var/www/html/personal-drive/database/db`

**Comment by mariushosting** [comment]
> [@CreakyLid](https://github.com/CreakyLid) have a fix. please do try.
> 
> NOTE: BREAKING CHANGE!!
> 
> * database location has changed ! its now  database/db/database.sqlite
> * the docker_compose.yml file has changed to accomodate this
> 
> So your `{myUnraidappdatapath}:/var/www/html/personal-drive/database` is now `{myUnraidappdatapath}:/var/www/html/personal-drive/database/db`

Looks like is now working. Nice job!

**Comment by gyaaniguy** [comment]
All good guys ?

I have updated the dockerfile and docker image so its smaller. 2.3GB ->  1.1GB

**Comment by gyaaniguy** [comment]
Closing as all seems well
